jasypt:
  encryptor:
    password: ${jasyptpwd:secretkey}
    algorithm: PBEWithMD5AndDES

server:
  port: 8084
  servlet:
    context-path: /predial
    session:
      timeout: 21600s

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:mysql://localhost:3306/pruebaceiba?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    hikari:
      poolName: pool
